### ISSUE TITLE
csfm.so: undefined symbol: cs_di_chol

### ISSUE THREAD

**Issue by smmmmi** [mapillary/OpenSfM#184]
Hi I built the "python setup.py build" without any problem but when trying "bin/opensfm_run_all data/berlin/" I get the following error:

```
~/OpenSfM$ bin/opensfm_run_all data/berlin/
Traceback (most recent call last):
  File "/home/mohammad/OpenSfM/bin/opensfm", line 10, in <module>
    from opensfm import commands
  File "/home/mohammad/OpenSfM/opensfm/commands/__init__.py", line 2, in <module>
    import extract_metadata
  File "/home/mohammad/OpenSfM/opensfm/commands/extract_metadata.py", line 5, in <module>
    from opensfm import dataset
  File "/home/mohammad/OpenSfM/opensfm/dataset.py", line 12, in <module>
    from opensfm import io
  File "/home/mohammad/OpenSfM/opensfm/io.py", line 10, in <module>
    from opensfm import features
  File "/home/mohammad/OpenSfM/opensfm/features.py", line 7, in <module>
    import csfm
ImportError: /home/mohammad/OpenSfM/opensfm/csfm.so: undefined symbol: cs_di_chol
```

Based on your previous replies in the net it is related to "ceres solver" but I already reinstalled it based on the guide at their page. Any ideas?

This is how the build went on:
```

~/OpenSfM$ python setup.py build
Configuring...
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Found OpenMP: -fopenmp  
-- Looking for dgemm_
-- Looking for dgemm_ - found
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE  
-- A library with BLAS API found.
-- Looking for cheev_
-- Looking for cheev_ - found
-- A library with LAPACK API found.
-- A library with BLAS API found.
-- Found AMD library: /usr/lib/x86_64-linux-gnu/libamd.so
-- Found AMD header in: /usr/include/suitesparse
-- Found CAMD library: /usr/lib/x86_64-linux-gnu/libcamd.so
-- Found CAMD header in: /usr/include/suitesparse
-- Found COLAMD library: /usr/lib/x86_64-linux-gnu/libcolamd.so
-- Found COLAMD header in: /usr/include/suitesparse
-- Found CCOLAMD library: /usr/lib/x86_64-linux-gnu/libccolamd.so
-- Found CCOLAMD header in: /usr/include/suitesparse
-- Found CHOLMOD library: /usr/lib/x86_64-linux-gnu/libcholmod.so
-- Found CHOLMOD header in: /usr/include/suitesparse
-- Found SuiteSparseQR library: /usr/lib/x86_64-linux-gnu/libspqr.so
-- Found SuiteSparseQR header in: /usr/include/suitesparse
-- Found Intel Thread Building Blocks (TBB) library: /usr/lib/x86_64-linux-gnu/libtbb.so, assuming SuiteSparseQR was compiled with TBB.
-- Found Intel Thread Building Blocks (TBB) Malloc library: /usr/lib/x86_64-linux-gnu/libtbbmalloc.so
-- Found SuiteSparse_config library: /usr/lib/x86_64-linux-gnu/libsuitesparseconfig.so
-- Found SuiteSparse_config header in: /usr/include/suitesparse
-- Adding librt: /usr/lib/x86_64-linux-gnu/librt.so to SuiteSparse_config libraries (required on Linux & Unix [not OSX] if SuiteSparse is compiled with timing).
-- Did not find METIS library (optional SuiteSparse dependency)
-- Found SuiteSparse: TRUE (found version "4.4.6") 
-- Found Eigen: /usr/local/include/eigen3 (found version "3.2.10") 
-- Found ceres: /usr/local/lib/libceres.a  
-- No preference for use of exported gflags CMake configuration set, and no hints for include/library directories provided. Defaulting to preferring an installed/exported gflags CMake configuration if available.
-- Found installed version of gflags: /usr/local/lib/cmake/gflags
-- Detected gflags version: 2.2.0
-- Found Gflags: /usr/local/include  
-- Found Glog: /usr/include  
-- Found CUDA: /usr/local/cuda (found suitable exact version "8.0") 
-- Found OpenCV: /usr/local (found suitable version "3.2.0", minimum required is "3.2.0") 
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   python
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython2.7.so (found version "2.7.12") 
-- Found PythonInterp: /usr/bin/python2.7 (found version "2.7.12") 
-- Found NumPy: version "1.12.1" /home/mohammad/.local/lib/python2.7/site-packages/numpy/core/include
-- Configuring done
-- Generating done
-- Build files have been written to: /home/mohammad/OpenSfM/cmake_build
Compiling extension...
Scanning dependencies of target akaze
Scanning dependencies of target gtest
Scanning dependencies of target vl
[  2%] Building CXX object CMakeFiles/gtest.dir/third_party/gtest/gmock_gtest_all.cc.o
[  4%] Building CXX object CMakeFiles/gtest.dir/third_party/gtest/gmock_main.cc.o
[  6%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/mathop.c.o
[  8%] Building CXX object CMakeFiles/akaze.dir/third_party/akaze/lib/AKAZE.cpp.o
[ 10%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/hikmeans.c.o
[ 12%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/quickshift.c.o
[ 14%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/getopt_long.c.o
[ 16%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/rodrigues.c.o
[ 18%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/scalespace.c.o
[ 20%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/imopv_sse2.c.o
[ 22%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/covdet.c.o
[ 24%] Building CXX object CMakeFiles/akaze.dir/third_party/akaze/lib/fed.cpp.o
[ 26%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/svmdataset.c.o
[ 28%] Building CXX object CMakeFiles/akaze.dir/third_party/akaze/lib/nldiffusion_functions.cpp.o
[ 30%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/generic.c.o
[ 32%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/lbp.c.o
[ 34%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/pgm.c.o
[ 36%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/dsift.c.o
[ 38%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/ikmeans.c.o
[ 40%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/slic.c.o
[ 42%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/fisher.c.o
[ 44%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/imopv.c.o
[ 46%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/svm.c.o
[ 48%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/mathop_avx.c.o
[ 51%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/vlad.c.o
[ 53%] Building CXX object CMakeFiles/akaze.dir/third_party/akaze/lib/utils.cpp.o
[ 55%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/host.c.o
[ 57%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/homkermap.c.o
[ 59%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/random.c.o
[ 61%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/kmeans.c.o
[ 63%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/mathop_sse2.c.o
[ 65%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/gmm.c.o
[ 67%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/sift.c.o
[ 69%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/kdtree.c.o
[ 71%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/stringop.c.o
[ 73%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/aib.c.o
[ 75%] Linking CXX static library libakaze.a
[ 75%] Built target akaze
[ 77%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/mser.c.o
[ 79%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/hog.c.o
[ 81%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/liop.c.o
[ 83%] Building C object CMakeFiles/vl.dir/third_party/vlfeat/vl/array.c.o
[ 85%] Linking C static library libvl.a
[ 85%] Built target vl
Scanning dependencies of target csfm
[ 87%] Building CXX object CMakeFiles/csfm.dir/csfm.cc.o
[ 89%] Linking CXX static library libgtest.a
[ 89%] Built target gtest
Scanning dependencies of target testing_main
[ 91%] Building CXX object CMakeFiles/testing_main.dir/testing_main.cc.o
[ 93%] Linking CXX static library libtesting_main.a
[ 93%] Built target testing_main
Scanning dependencies of target depthmap_test
[ 95%] Building CXX object CMakeFiles/depthmap_test.dir/depthmap_test.cc.o
[ 97%] Linking CXX executable depthmap_test
[ 97%] Built target depthmap_test
[100%] Linking CXX shared library /home/mohammad/OpenSfM/opensfm/csfm.so
[100%] Built target csfm
Building package
running build
running build_py
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/opensfm
copying opensfm/dense.py -> build/lib.linux-x86_64-2.7/opensfm
copying opensfm/dataset.py -> build/lib.linux-x86_64-2.7/opensfm
copying opensfm/unionfind.py -> build/lib.linux-x86_64-2.7/opensfm
copying opensfm/multiview.py -> build/lib.linux-x86_64-2.7/opensfm
copying opensfm/video.py -> build/lib.linux-x86_64-2.7/opensfm
copying opensfm/exif.py -> build/lib.linux-x86_64-2.7/opensfm
copying opensfm/align.py -> build/lib.linux-x86_64-2.7/opensfm
copying opensfm/transformations.py -> build/lib.linux-x86_64-2.7/opensfm
copying opensfm/__init__.py -> build/lib.linux-x86_64-2.7/opensfm
copying opensfm/context.py -> build/lib.linux-x86_64-2.7/opensfm
copying opensfm/reconstruction.py -> build/lib.linux-x86_64-2.7/opensfm
copying opensfm/geotag_from_gpx.py -> build/lib.linux-x86_64-2.7/opensfm
copying opensfm/sensors.py -> build/lib.linux-x86_64-2.7/opensfm
copying opensfm/matching.py -> build/lib.linux-x86_64-2.7/opensfm
copying opensfm/geo.py -> build/lib.linux-x86_64-2.7/opensfm
copying opensfm/features.py -> build/lib.linux-x86_64-2.7/opensfm
copying opensfm/mesh.py -> build/lib.linux-x86_64-2.7/opensfm
copying opensfm/io.py -> build/lib.linux-x86_64-2.7/opensfm
copying opensfm/config.py -> build/lib.linux-x86_64-2.7/opensfm
copying opensfm/types.py -> build/lib.linux-x86_64-2.7/opensfm
creating build/lib.linux-x86_64-2.7/opensfm/commands
copying opensfm/commands/match_features.py -> build/lib.linux-x86_64-2.7/opensfm/commands
copying opensfm/commands/reconstruct.py -> build/lib.linux-x86_64-2.7/opensfm/commands
copying opensfm/commands/compute_depthmaps.py -> build/lib.linux-x86_64-2.7/opensfm/commands
copying opensfm/commands/__init__.py -> build/lib.linux-x86_64-2.7/opensfm/commands
copying opensfm/commands/export_ply.py -> build/lib.linux-x86_64-2.7/opensfm/commands
copying opensfm/commands/extract_metadata.py -> build/lib.linux-x86_64-2.7/opensfm/commands
copying opensfm/commands/create_tracks.py -> build/lib.linux-x86_64-2.7/opensfm/commands
copying opensfm/commands/detect_features.py -> build/lib.linux-x86_64-2.7/opensfm/commands
copying opensfm/commands/export_visualsfm.py -> build/lib.linux-x86_64-2.7/opensfm/commands
copying opensfm/commands/export_openmvs.py -> build/lib.linux-x86_64-2.7/opensfm/commands
copying opensfm/commands/mesh.py -> build/lib.linux-x86_64-2.7/opensfm/commands
copying opensfm/commands/undistort.py -> build/lib.linux-x86_64-2.7/opensfm/commands
copying opensfm/csfm.so -> build/lib.linux-x86_64-2.7/opensfm
creating build/lib.linux-x86_64-2.7/opensfm/data
copying opensfm/data/sensor_data.json -> build/lib.linux-x86_64-2.7/opensfm/data
running build_scripts
creating build/scripts-2.7
copying bin/opensfm_run_all -> build/scripts-2.7
copying and adjusting bin/opensfm -> build/scripts-2.7
changing mode of build/scripts-2.7/opensfm from 664 to 775

```

**Comment by smmmmi** [comment]
Related to #41

**Comment by paulinus** [comment]
@smmmmi i don't know what the problem is. I can only think of linking problems.

Did you make sure to use the `-fPIC` option when building Ceres?

The configuration command should look like this
```bash
cd path/to/ceres-solver-1.10.0/build
cmake .. -DCMAKE_C_FLAGS=-fPIC -DCMAKE_CXX_FLAGS=-fPIC -DBUILD_EXAMPLES=OFF -DBUILD_TESTING=OFF
make install
```

**Comment by kvas7andy** [comment]
Hi,

I have the same error. After searching  via Internet I didn't found any solution. 
I have Ubuntu 16.04. There was no repository for libsuitesparse library available, so I had to download package from source and install everything via make install.
I made installation by your Dockfile script. 

Could you help me please, what should be useful to provide?

**Comment by smmmmi** [comment]
I tried the hint @paulinus gave but I got the same ImportError.
Issue remains open!

**Comment by kvas7andy** [comment]
To totally remove paste build I delete directories build and cmake_build, but I don't know is it enough?

**Comment by kvas7andy** [comment]
Ok, I think that's ubuntu 16 related problem. 

And the solution is to user `docker-ce` in order to run all files in docker.
Guys install docker and build image with Dockerfile, than use it as container with `docker run`.
Sorry for the question, because the solution was obvious, but not for me, as I didn't have any experience with docker. Please, @mapillary-ci , insert some description in README file, why to use docker, and not to install everything in system by our own. Thanx for the good lib!

**Comment by nlpguyz** [comment]
Same problem on Ubuntu 14. Is docker still the only solution?

**Comment by rjeli** [comment]
@nlpguyz I have just fixed this error. The last thing I did before it worked was to build ceres as a shared library. Before that I also built SuiteSparse and CXSparse from source.

**Comment by nlpguyz** [comment]
@rjeli Thanks for the information. I got it to work using docker. Now I will try to build ceres as a shared library. thanks.

**Comment by jomnipotent17** [comment]
I also encountered this problem. What happened in my case was that I had updated to the newest version of ceres-solver and then I started getting the error. So, I reverted back to ceres-solver-1.10.0 and it fixed the problem. Hope that helps someone!

**Comment by JohnTailor** [comment]
It still does not work for me... I get  "opensfm/csfm.so: undefined symbol: cs_di_chol" ...
I tried everything above: 
 - "docker build ."
- building SuiteSparse and CXSparse from source (I think cs_di_chol should be in there -> I could see it at least in this lib, eg. I used " nm -gC libcxsparse.a |grep cs_di_chol"  => One should get  ... "T cs_di_chol" which means it is defined, but one line below I got "U cs_di_chol" which means it is undefined and totally contradictionary)
- manual build (based on docker)
- went back to ceres-solver-1.10.0  (there is some note in the commits saying that cxsparse can be replaced eigen in that version)

My personal guess is that there are issues with the libraries and linking. I recently install opencv and the contrib stuff, this also required similar libs. Spend lots of time on it. Any help appreciated.

**Comment by hy9be** [comment]
Must be a dummy question, but how did you guys managed to build with Cuda. I have Cuda installed on my machine and it works fine with Tensorflow and darknet yolo. But when I build Opensfm, the compile log did not have that Cuda line:

```
-- Found CUDA: /usr/local/cuda (found suitable exact version "8.0") 
```

Could anyone shed some lights? @smmmmi

**Comment by paulinus** [comment]
@hy9be, opensfm does not use Cuda
